### ISSUE TITLE
SUNNYVALE → dddNYVALE

### ISSUE THREAD

**Issue by jedwards1211** [gr2m/moment-parseformat#67] opened 2017-07-21 17:14 UTC
Obviously this isn't a date, because I'm using `parseFormat` to help look for dates and times in CSV data.
`moment.parseFormat('SUNNYVALE')` parsed to `dddNYVALE`, I expected: `SUNNYVALE` (or `null`)

I think we should exclude any month/day name or abbrev matches that have adjacent letters.

**Comment by gr2m** [comment] 2017-07-21 17:50
I think your use case is out of scope of `parseFormat`. If your data comes out of a CSV, maybe do a pre-cleanup before you pass the date string into `parseFormat`? 

`parseFormat` is meant to understand human-input of date/time strings. `SUNNYVALE` is not something a human would enter, the problem is somewhere else and I would resolve the problem outside of `parseFormat`

**Closed** 2017-07-21 21:07 UTC
