### ISSUE TITLE
2015 02 03 → YYYY DD D

### ISSUE THREAD

**Issue by jedwards1211** [gr2m/moment-parseformat#70] opened 2017-07-21 19:59 UTC
`moment.parseFormat('2015 02 03')` parsed to `YYYY DD D`, I expected: `YYYY MM DD`

**Comment by johnnyNcsu** [comment] 2018-10-05 22:07
I am also seeing this issue with date strings of form '09-15' -> DD-D; expected MM-DD (moment treats as MM-DD).

Similarly, inputs for '09' -> DD (moment treats as MM) and '12' -> D (moment treats as MM).

And 'March 28, 2001' -> MMMM D, YYYY (this may be technically ok but I would think a better result would be MMMM DD, YYYY).

**Comment by gr2m** [comment] 2018-10-05 22:53
I don’t think that `09-15` or `09` would be useful input to be parsed with this library. I’d be okay to add proper parsing for `YYYY M D` / `YYYY MM DD`, although I have never seen this date format myself and given the issue is open for so long and nobody adding their +1s, it’s maybe too much of an edge case to be considered.

**Comment by gr2m** [comment] 2018-10-06 15:11
>  I am looking for a library that exposes the internal momentjs format string used to interpret the input if it (momentjs) determines that input to be a valid date string

I think momentjs is just passing the string to the native `Date` object that might or might not be able to parse the string correctly, it’s different based on the JavaScript runtime environment. I don’t think you can get access to the input format used to parse the string. This library is doing all the parsing by hand with lots and lots of regex :)

I use parseFormat to parse dates entered by humans. The idea is that someone can enter a date in a free text form and the app can understand both the entered date/time as well as the preferred date format of the user.

**Comment by johnnyNcsu** [comment] 2018-10-06 15:54
> I think momentjs is just passing the string to the native Date object that might or might not be able to parse the string correctly

@gr2m Thanks. Yes, this makes sense and likely explains why momentjs does not seem to expose parsed date fields - even though they appear to have some notion of this in their parse flags object (_pf.parsedDateParts). It seems to be an empty array every time I check it.

I will spend more time with momentjs to try too understand it a bit better. There do appear to be cases where momentjs is making some attempt to interpret date strings before calling `Date` on the string (e.g. a string of "2001" is interpreted as the year 2001 by momentjs but native `Date` will interpret this as 2001 milliseconds). Perhaps this is a feature request better placed with momentjs - although the opaqueness of the native `Date` object may impose significant challenges for fulfilling this request.

Thanks again!

**Comment by gr2m** [comment] 2018-10-06 17:59
Keep me posted :) I’ll close this issue for the time being, maybe open a new issue if you have a plan™️

**Closed by gr2m** 2018-10-06 17:59 UTC
